config/routes.rb
# ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "routes.rb" do not modify this file, your changes will be clobbered!
# #################################

Rails.application.routes.draw do

  get '/', to: 'framework#home', as: 'home'
  get '/about', to: 'framework#about', as: 'about'


# routes for the "Developer's view of EmployeePhone" view
  get '/employee_phones', to: 'employee_phones#index', as: 'employee_phones'
  get '/employee_phones/new', to: 'employee_phones#new', as: 'new_employee_phone'
  get '/employee_phones/:id/edit', to: 'employee_phones#edit', as: 'edit_employee_phone'
  get '/employee_phones/:id', to: 'employee_phones#show', as: 'employee_phone'
  post '/employee_phones', to: 'employee_phones#create'
  put '/employee_phones/:id', to: 'employee_phones#update'
  patch '/employee_phones/:id', to: 'employee_phones#update'
  delete '/employee_phones/:id', to: 'employee_phones#destroy'

# routes for the "Developer's view of Employee" view
  get '/employees', to: 'employees#index', as: 'employees'
  get '/employees/new', to: 'employees#new', as: 'new_employee'
  get '/employees/:id/edit', to: 'employees#edit', as: 'edit_employee'
  get '/employees/:id', to: 'employees#show', as: 'employee'
  post '/employees', to: 'employees#create'
  put '/employees/:id', to: 'employees#update'
  patch '/employees/:id', to: 'employees#update'
  delete '/employees/:id', to: 'employees#destroy'

# routes for the "Developer's view of PhoneType" view
  get '/phone_types', to: 'phone_types#index', as: 'phone_types'
  get '/phone_types/new', to: 'phone_types#new', as: 'new_phone_type'
  get '/phone_types/:id/edit', to: 'phone_types#edit', as: 'edit_phone_type'
  get '/phone_types/:id', to: 'phone_types#show', as: 'phone_type'
  post '/phone_types', to: 'phone_types#create'
  put '/phone_types/:id', to: 'phone_types#update'
  patch '/phone_types/:id', to: 'phone_types#update'
  delete '/phone_types/:id', to: 'phone_types#destroy'

# routes for the "Developer's view of Division" view
  get '/divisions', to: 'divisions#index', as: 'divisions'
  get '/divisions/new', to: 'divisions#new', as: 'new_division'
  get '/divisions/:id/edit', to: 'divisions#edit', as: 'edit_division'
  get '/divisions/:id', to: 'divisions#show', as: 'division'
  post '/divisions', to: 'divisions#create'
  put '/divisions/:id', to: 'divisions#update'
  patch '/divisions/:id', to: 'divisions#update'
  delete '/divisions/:id', to: 'divisions#destroy'

# routes for the "Developer's view of Company" view
  get '/companies', to: 'companies#index', as: 'companies'
  get '/companies/new', to: 'companies#new', as: 'new_company'
  get '/companies/:id/edit', to: 'companies#edit', as: 'edit_company'
  get '/companies/:id', to: 'companies#show', as: 'company'
  post '/companies', to: 'companies#create'
  put '/companies/:id', to: 'companies#update'
  patch '/companies/:id', to: 'companies#update'
  delete '/companies/:id', to: 'companies#destroy'

# routes for the "Developer's view of Country" view
  get '/countries', to: 'countries#index', as: 'countries'
  get '/countries/new', to: 'countries#new', as: 'new_country'
  get '/countries/:id/edit', to: 'countries#edit', as: 'edit_country'
  get '/countries/:id', to: 'countries#show', as: 'country'
  post '/countries', to: 'countries#create'
  put '/countries/:id', to: 'countries#update'
  patch '/countries/:id', to: 'countries#update'
  delete '/countries/:id', to: 'countries#destroy'

# routes for the "Our Company Structure" view
  get '/cmp_lst/employees', to: 'cmp_lst/employees#index', as: 'cmp_lst_employees'
  get '/cmp_lst/employees/:id', to: 'cmp_lst/employees#show', as: 'cmp_lst_employee'
  get '/cmp_lst/divisions', to: 'cmp_lst/divisions#index', as: 'cmp_lst_divisions'
  get '/cmp_lst/divisions/:id', to: 'cmp_lst/divisions#show', as: 'cmp_lst_division'
  get '/cmp_lst/companies', to: 'cmp_lst/companies#index', as: 'cmp_lst_companies'
  get '/cmp_lst/companies/:id', to: 'cmp_lst/companies#show', as: 'cmp_lst_company'

# routes for the "Manage Company Staff" view
  get '/mng_stff/employees', to: 'mng_stff/employees#index', as: 'mng_stff_employees'
  get '/mng_stff/employees/new', to: 'mng_stff/employees#new', as: 'new_mng_stff_employee'
  get '/mng_stff/employees/:id/edit', to: 'mng_stff/employees#edit', as: 'edit_mng_stff_employee'
  get '/mng_stff/employees/:id', to: 'mng_stff/employees#show', as: 'mng_stff_employee'
  post '/mng_stff/employees', to: 'mng_stff/employees#create'
  put '/mng_stff/employees/:id', to: 'mng_stff/employees#update'
  patch '/mng_stff/employees/:id', to: 'mng_stff/employees#update'
  delete '/mng_stff/employees/:id', to: 'mng_stff/employees#destroy'

# routes for the "Company Structure" view
  get '/mng_cmp/employees', to: 'mng_cmp/employees#index', as: 'mng_cmp_employees'
  get '/mng_cmp/employees/:id', to: 'mng_cmp/employees#show', as: 'mng_cmp_employee'
  get '/mng_cmp/divisions', to: 'mng_cmp/divisions#index', as: 'mng_cmp_divisions'
  get '/mng_cmp/divisions/new', to: 'mng_cmp/divisions#new', as: 'new_mng_cmp_division'
  get '/mng_cmp/divisions/:id/edit', to: 'mng_cmp/divisions#edit', as: 'edit_mng_cmp_division'
  get '/mng_cmp/divisions/:id', to: 'mng_cmp/divisions#show', as: 'mng_cmp_division'
  post '/mng_cmp/divisions', to: 'mng_cmp/divisions#create'
  put '/mng_cmp/divisions/:id', to: 'mng_cmp/divisions#update'
  patch '/mng_cmp/divisions/:id', to: 'mng_cmp/divisions#update'
  delete '/mng_cmp/divisions/:id', to: 'mng_cmp/divisions#destroy'
  get '/mng_cmp/companies', to: 'mng_cmp/companies#index', as: 'mng_cmp_companies'
  get '/mng_cmp/companies/new', to: 'mng_cmp/companies#new', as: 'new_mng_cmp_company'
  get '/mng_cmp/companies/:id/edit', to: 'mng_cmp/companies#edit', as: 'edit_mng_cmp_company'
  get '/mng_cmp/companies/:id', to: 'mng_cmp/companies#show', as: 'mng_cmp_company'
  post '/mng_cmp/companies', to: 'mng_cmp/companies#create'
  put '/mng_cmp/companies/:id', to: 'mng_cmp/companies#update'
  patch '/mng_cmp/companies/:id', to: 'mng_cmp/companies#update'
  delete '/mng_cmp/companies/:id', to: 'mng_cmp/companies#destroy'


end

app/models/division.rb
# ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "write-model-class" do not modify this file, your changes will be clobbered!
# #################################

class Division < ApplicationRecord

  #  relationships
  belongs_to :operational_manager, class_name: "Employee"
  belongs_to :company

  #  validations
  validates :status, presence: { message: "all %{model} records require a value for the %{attribute} field. " }
  validates :status, inclusion: 
    { in: ["active", "dormant", "archived"],
      message: "Status value must be one of \"active\", \"dormant\", or \"archived\". \"%{value}\" is not in there"}
  validates :name, uniqueness: { message: "all %{model} records must have a unique Division Name value. \"%{value}\" is taken" }
  validates :name, presence: { message: "all %{model} records require a value for the %{attribute} field. " }
  validates :code, format: 
    { message: "all %{attribute} values must match a pattern. ",
      with: /\A[a-zA-Z0-9_.-]{0,10}\z/}
  validates :code, uniqueness: { message: "all %{model} records must have a unique Division Code value. \"%{value}\" is taken" }
  validates :code, presence: { message: "all %{model} records require a value for the %{attribute} field. " }

end

app/controllers/cmp_lst/divisions_controller.rb
# ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "write-controller-files" do not modify this file, your changes will be clobbered!
# #################################
class CmpLst::DivisionsController < ApplicationController
  before_action :set_division, only: [:show, :edit, :update, :destroy]

  # GET /cmp_lst/divisions
  # GET /cmp_lst/divisions.json
  def index
    @divisions = Division.all
  end

  # GET /cmp_lst/divisions/:id
  # GET /cmp_lst/divisions/:id.json
  def show
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_division
    @division = Division.find(params[:id])
  end



end

app/controllers/divisions_controller.rb
# ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "write-controller-files" do not modify this file, your changes will be clobbered!
# #################################
class DivisionsController < ApplicationController
  before_action :set_division, only: [:show, :edit, :update, :destroy]

  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all
  end

  # GET /divisions/:id
  # GET /divisions/:id.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new()
  end

  # GET /divisions/:id/edit
  def edit
  end

  # POST /divisions
  def create
    @division = Division.new(division_params)
    respond_to do |format|
      if @division.save
        format.html { redirect_to division_path(@division), notice: 'Your Division record was successfully created.' }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/:id
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to division_path(@division), notice: 'Your Division record was successfully updated.' }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/:id
  def destroy
    @division.destroy
    respond_to do |format|
      format.html { redirect_to divisions_url, notice: 'Your Division record was successfully deleted.' }
      format.json { head :no_content }
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_division
    @division = Division.find(params[:id])
  end


  # Only allow a list of trusted parameters through.
  def division_params
    params.require(:division).permit(:operational_manager_id, :company_id, :status, :description, :name, :code, :op_mark)
  end

end

app/controllers/mng_cmp/companies_controller.rb
# ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "write-controller-files" do not modify this file, your changes will be clobbered!
# #################################
class MngCmp::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /mng_cmp/companies
  # GET /mng_cmp/companies.json
  def index
    @companies = Company.all
  end

  # GET /mng_cmp/companies/:id
  # GET /mng_cmp/companies/:id.json
  def show
  end

  # GET /mng_cmp/companies/new
  def new
    @company = Company.new()
  end

  # GET /mng_cmp/companies/:id/edit
  def edit
  end

  # POST /mng_cmp/companies
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        format.html { redirect_to mng_cmp_company_path(@company), notice: 'Your Company record was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mng_cmp/companies/:id
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to mng_cmp_company_path(@company), notice: 'Your Company record was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mng_cmp/companies/:id
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to mng_cmp_companies_url, notice: 'Your Company record was successfully deleted.' }
      format.json { head :no_content }
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end


  # Only allow a list of trusted parameters through.
  def company_params
    params.require(:company).permit(:code, :name, :company_type, :description)
  end

end

app/controllers/mng_cmp/divisions_controller.rb
# ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "write-controller-files" do not modify this file, your changes will be clobbered!
# #################################
class MngCmp::DivisionsController < ApplicationController
  before_action :set_division, only: [:show, :edit, :update, :destroy]

  # GET /mng_cmp/divisions
  # GET /mng_cmp/divisions.json
  def index
    @divisions = Division.all
  end

  # GET /mng_cmp/divisions/:id
  # GET /mng_cmp/divisions/:id.json
  def show
  end

  # GET /mng_cmp/divisions/new
  def new
    @division = Division.new()
  end

  # GET /mng_cmp/divisions/:id/edit
  def edit
  end

  # POST /mng_cmp/divisions
  def create
    @division = Division.new(division_params)
    respond_to do |format|
      if @division.save
        format.html { redirect_to mng_cmp_division_path(@division), notice: 'Your Division record was successfully created.' }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mng_cmp/divisions/:id
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to mng_cmp_division_path(@division), notice: 'Your Division record was successfully updated.' }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mng_cmp/divisions/:id
  def destroy
    @division.destroy
    respond_to do |format|
      format.html { redirect_to mng_cmp_divisions_url, notice: 'Your Division record was successfully deleted.' }
      format.json { head :no_content }
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_division
    @division = Division.find(params[:id])
  end


  # Only allow a list of trusted parameters through.
  def division_params
    params.require(:division).permit(:code, :name, :operational_manager_id, :status, :description)
  end

end

app/controllers/mng_cmp/employees_controller.rb
# ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "write-controller-files" do not modify this file, your changes will be clobbered!
# #################################
class MngCmp::EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /mng_cmp/employees
  # GET /mng_cmp/employees.json
  def index
    @employees = Employee.all
  end

  # GET /mng_cmp/employees/:id
  # GET /mng_cmp/employees/:id.json
  def show
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end



end

app/views/mng_cmp/divisions/_form.html.erb
<% # ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "_form.html.erb" do not modify this file, your changes will be clobbered!
# #################################
 %>
<%= form_with(model: [:mng_cmp, division]) do |form| %>
<% if division.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(division.errors.count, "error") %> prevented this Division from saving:</h2>
      <ul>
       <% division.errors.each do |error| %>
        <li><%= error.full_message %></li>
       <% end %></ul>
  </div>
<% end %>

  <table>
  <tbody>
  <tr>
    <td><div class="field">
  <%= form.label "Division Code" %>
  <%= form.text_field :code %>
</div></td>
    <td><div class="field">
  <%= form.label "Division Name" %>
  <%= form.text_field :name %>
</div></td>
    <td><div class="field">
  <%= form.label "Operational Manager" %>
  <%= form.collection_select :operational_manager_id, Employee.order(:code), :id, :first_last_name, :prompt => 'please select', :include_blank => false %>
</div></td>
  </tr>
  <tr>
    <td><div class="field">
  <%= form.label "Description" %>
  <%= form.text_area :description, size: "70x4" %>
</div></td>
  </tr></tbody>
</table>
<div class="actions"><%= form.submit %></div>
<% end %>

app/views/mng_cmp/divisions/edit.html.erb
<% # ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "edit.html.erb" do not modify this file, your changes will be clobbered!
# #################################
 %>
<h1>Editing Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Show', mng_cmp_division_path(@division) %>
<%= link_to 'Hide Details', mng_cmp_divisions_path %>

app/views/mng_cmp/divisions/index.html.erb
<% # ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "index.html.erb" do not modify this file, your changes will be clobbered!
# #################################
 %>
<p id="notice"><%= notice %></p>
<h1>Company Structures - Divisions</h1>
<table border="1">
  <thead>
  <tr>
    <th colspan="3">(actions)</th>
    <th>Code</th>
    <th>Name</th>
    <th>Operational Manager Full Name</th>
    <th>Description</th>
  </tr>
</thead>
  <tbody>
<% @divisions.each do |division| %>
  <tr>
    <td><%= link_to 'Show', mng_cmp_division_path(division) %></td>
    <td><%= link_to 'Edit', edit_mng_cmp_division_path(division) %></td>
    <td><%= link_to 'Delete', mng_cmp_division_path(division), method: :delete, data: { confirm: 'Are you sure? You are about to delete this record.' } %></td>
      <td><%= division.code.to_s %></td>
      <td><%= division.name.to_s %></td>
      <td><%= Employee.find_by_id(division.operational_manager_id).first_last_name %></td>
      <td><%= division.description.to_s %></td>
  </tr>
<% end %></tbody>
</table>
<br>

<%= link_to 'New Division', new_mng_cmp_division_path %>

app/views/mng_cmp/divisions/new.html.erb
<% # ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "new.html.erb" do not modify this file, your changes will be clobbered!
# #################################
 %>
<h1>New Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Hide Details', mng_cmp_divisions_path %>

app/views/mng_cmp/divisions/show.html.erb
<% # ######################################
# this file was generated on Wednesday November 10, 2021 at 10:48:22 AEDT by
# "show.html.erb" do not modify this file, your changes will be clobbered!
# #################################
 %>
<p id="notice"><%= notice %></p>
  <table border="1">
    <tbody>
    <tr>
<td><strong>Division Name:</strong></td>
<td><%= @division.name.to_s %></td>

<td><strong>Division Code:</strong></td>
<td><%= @division.code.to_s %></td>
</tr>
    <tr>
<td><strong>Operational Manager Full Name:</strong></td>
<td><%= Employee.find_by_id(@division.operational_manager_id).first_last_name %></td>

<td><strong>Status:</strong></td>
<td><%= @division.status.to_s %></td>
</tr>
    <tr>
<td><strong>Description:</strong></td>
<td><%= @division.description.to_s %></td>
</tr></tbody>
  </table>
<%= link_to 'Edit', edit_mng_cmp_division_path(@division) %>
<%= link_to 'Delete', mng_cmp_division_path(@division), method: :delete, data: { confirm: 'Are you sure? You are about to delete this record.' } %>
<%= link_to 'Hide Details', mng_cmp_divisions_path %>

<%= link_to 'New Division', new_mng_cmp_division_path %>